[[mgr.prepend_keymap]]
on = "N"
run = '''
shell '
    nsxiv --anti-alias=no "$1"
' -- $1
'''
desc = "nsxiv_open"

[[mgr.prepend_keymap]]
on = "'"
run = '''
shell --block '
    hx "$1"
' -- $1
'''
desc = "helix_open"

[[mgr.prepend_keymap]]
on  = [ "+", "x" ]
run = '''
shell '
    chmod +x "$1"
' -- $1
'''
desc = "chmodx"

[[mgr.prepend_keymap]]
on  = [ "c", "p" ]
run = "copy dirname"
desc = "copy_path"

[[mgr.prepend_keymap]]
on  = [ "c", "d" ]
run = "plugin zoxide"
desc = "change_dir"

[[mgr.prepend_keymap]]
on  = [ "g", "b" ]
run = "cd ~/.baby"
desc = "go_baby"

[[mgr.prepend_keymap]]
on  = [ "g", "s" ]
run = "cd ~/scripts"
desc = "go_scripts"

[[mgr.prepend_keymap]]
on  = [ "g", "o" ]
run = 'cd ~/Documents/obsidian_vault'
desc = "go_obsidian"

[[mgr.prepend_keymap]]
on  = [ "g", "l" ]
run = "cd ~/.local"
desc = "go_local"

[[mgr.prepend_keymap]]
on  = [ "g", "w" ]
run = "cd ~/Pictures/wallpapers"
desc = "go_wallpapers"

[[mgr.prepend_keymap]]
on  = [ "g", "p" ]
run = "cd ~/.cache/wal"
desc = "go_pywal"

[[mgr.prepend_keymap]]
on  = "H"
run = "tab_switch -1 --relative"
desc = "prevtab"

[[mgr.prepend_keymap]]
on  = "L"
run = "tab_switch 1 --relative"
desc = "nexttab"

[[mgr.prepend_keymap]]
on   = "="
run  = "plugin zoom 1"
desc = "zoom_in"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "zoom_out"
