--autoinstall
local data_dir = vim.fn.stdpath('data')
if vim.fn.empty(vim.fn.glob(data_dir .. '/site/autoload/plug.vim')) == 1 then
    vim.cmd('silent !curl -fLo ' .. data_dir .. '/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
    vim.o.runtimepath = vim.o.runtimepath
    vim.cmd('autocmd VimEnter * PlugInstall --sync | source $MYVIMRC')
end

local vim = vim
local Plug = vim.fn['plug#']

vim.cmd("filetype plugin on")

vim.call('plug#begin')

--colors
Plug('catppuccin/nvim', { ['as'] = 'catppuccin' })
Plug('rose-pine/neovim', { ['as'] = 'rose-pine' })
Plug('sainnhe/edge')
Plug('sainnhe/sonokai')
Plug('sainnhe/everforest')
Plug('sainnhe/gruvbox-material')
Plug('rebelot/kanagawa.nvim')
Plug('folke/tokyonight.nvim')
Plug('ayu-theme/ayu-vim')
Plug('ribru17/bamboo.nvim')
Plug('uloco/bluloco.nvim')
Plug('webhooked/kanso.nvim')
Plug('kamwitsta/vinyl.nvim')
Plug('NLKNguyen/papercolor-theme')
Plug('dylanaraps/wal.vim')

--plugins
Plug('nvim-tree/nvim-web-devicons')
Plug('folke/which-key.nvim')
Plug('goolord/alpha-nvim')
Plug('nvim-treesitter/nvim-treesitter')
Plug('nvim-treesitter/playground')
Plug('mfussenegger/nvim-lint')
Plug('windwp/nvim-autopairs')
Plug('lewis6991/gitsigns.nvim')
Plug('numToStr/Comment.nvim')
Plug('norcalli/nvim-colorizer.lua')
Plug('ibhagwan/fzf-lua')
Plug('zaldih/themery.nvim')
Plug('drgfunk/streamline.nvim')
Plug('echasnovski/mini.icons')
Plug('MunifTanjim/nui.nvim')
Plug('rcarriga/nvim-notify')
Plug('folke/noice.nvim')
Plug('nvim-lua/plenary.nvim')
Plug('obsidian-nvim/obsidian.nvim')
Plug('MeanderingProgrammer/render-markdown.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nanozuki/tabby.nvim')
Plug('mikavilpas/yazi.nvim')
Plug('folke/flash.nvim')
Plug('echasnovski/mini.surround')
Plug('declancm/cinnamon.nvim')
Plug('tidalcycles/vim-tidal')
Plug('neovim/nvim-lspconfig')
Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
--Plug('davidgranstrom/scnvim')
--Plug('robbielyman/tidal.nvim')
Plug('mrcjkb/rustaceanvim')

vim.call('plug#end')

--load
require("config.autocmd")
require("config.filetypes")
require("config.mappings")
require("config.options")
require("config.transparent")

require("plugins.alpha")
require("plugins.autopairs")
require("plugins.colorizer")
require("plugins.comment")
--require("plugins.fzf-lua")
require("plugins.gitsigns")
require("plugins.noice")
require("plugins.notify")
require("plugins.nvim-lint")
--require("plugins.obsidian")
require("plugins.render-markdown")
require("plugins.streamline")
require("plugins.tabby")
require("plugins.telescope")
require("plugins.themery")
require("plugins.treesitter")
require("plugins.which-key")
require("plugins.yazi")
require("plugins.flash")
require("plugins.cinnamon")
require("mini.surround").setup({})
require("plugins.mason")
