local wk = require("which-key")
wk.setup({
    preset = "helix",
    win = {
        title = false,
        title_pos = "center",
    },
    icons = {
        separator = " ",
        breadcrumb = "▸",
    },
})
wk.add({
    { "<leader>c", desc = " theme", icon = "" },
    { "<leader>y", desc = " yazi", icon = "󰀶" },
    { "<leader>u", desc = " openurl", icon = "" },
    { "<leader>g", desc = " grep", icon = "" },
    { "<leader>x", desc = " chmod", icon = "" },
    { "<leader>r", desc = " reload", icon = "" },
    { "<leader>w", desc = " wrap", icon = "" },
    { "<leader>p", desc = " plug", icon = "" },
    { "<leader>t", desc = " telescope", icon = "" },
    { "<leader>fz", desc = " find_cwd", icon = "" },
    { "<leader>f~", desc = " find_home", icon = "" },
    { "<leader>f.", desc = " find_.cfg", icon = "" },
    { "<leader>fh", desc = " find_help", icon = "" },
    { "<leader>fc", desc = " find_rgstr", icon = "" },
    { "<leader>fy", desc = " find_cmds", icon = "" },
    { "<leader>fr", desc = " find_rcnts", icon = "" },
    { "<leader>fm", desc = " find_manpg", icon = "" },
    { "<leader>,", desc = " macro_rec", icon = "󰟠" },
    { "<leader>.", desc = " macro_play", icon = "󰟟" },
    { "<leader>d", desc = " daddybear", icon = "󱣻" },
    { "<leader>lr", desc = " lsp_rename", icon = "" },
    { "<leader>la", desc = " lsp_action", icon = "" },
    { "<leader>ld", desc = " lsp_jumpdef", icon = "" },
    { "<leader>li", desc = " lsp_implem", icon = "" },
    { "<leader>lh", desc = " lsp_hover", icon = "" },
    { "<leader>ls", desc = " lsp_signat", icon = "" },
    { "<leader>lf", desc = " lsp_format", icon = "" },
    { "<leader>le", desc = " lsp_float", icon = "" },
    { "<leader>lq", desc = " lsp_loclist", icon = "" },
    { "<leader>l[", desc = " lsp_diagnxt", icon = "" },
    { "<leader>l]", desc = " lsp_dianprv", icon = "" },
})
